"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import CustomerShell from "@/components/CustomerShell";
import { api } from "@/lib/api";
import { AlertCircle, ArrowLeft, CheckCircle2, CircleDashed, Database, Package, RefreshCw, Sparkles } from "lucide-react";

type Product={id:string;name:string;sku?:string|null;stock:number|null;stockStatus:"IN_STOCK"|"OUT_OF_STOCK"|"LOW_STOCK"|"UNKNOWN";isActive:boolean;lastSyncedAt?:string|null;source?:string};
type Response={success:boolean;products:Product[];pagination?:{total:number}};
const fa=(n:number)=>new Intl.NumberFormat("fa-IR").format(n);
const statusLabel=(p:Product)=>p.stockStatus==="IN_STOCK"?"موجود":p.stockStatus==="OUT_OF_STOCK"?"ناموجود":p.stockStatus==="LOW_STOCK"?"رو به اتمام":p.stock==null?"نامشخص":"دارای موجودی";
export default function ProductAnalysisPage(){
 const [products,setProducts]=useState<Product[]>([]);const [total,setTotal]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await api<Response>("/agent/products?page=1&limit=100");setProducts(r.products||[]);setTotal(r.pagination?.total??r.products?.length??0);}catch(e){setError(e instanceof Error?e.message:"دریافت کاتالوگ ناموفق بود.");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const active=products.filter(p=>p.isActive).length;const known=products.filter(p=>p.stock!==null||p.stockStatus!=="UNKNOWN").length;const low=products.filter(p=>p.stockStatus==="LOW_STOCK"||(p.stock!==null&&p.stock>0&&p.stock<=5)).length;const out=products.filter(p=>p.stockStatus==="OUT_OF_STOCK"||p.stock===0).length;
 const cards=[{label:"کل محصولات",value:total,icon:Package},{label:"محصولات فعال",value:active,icon:CheckCircle2},{label:"موجودی نامشخص",value:Math.max(0,products.length-known),icon:CircleDashed},{label:"کم‌موجود یا ناموجود",value:low+out,icon:AlertCircle}];
 return <CustomerShell><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold text-[#10706B]">هوش محصول / تحلیل</p><h1 className="text-2xl font-black">وضعیت کاتالوگ محصولات</h1><p className="mt-2 text-sm text-[#7D8D89]">این صفحه از محصولات واقعی API گزارش می‌سازد؛ پردازش هوش مصنوعی جداگانه فقط در صورت وجود سرویس آن نمایش داده می‌شود.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-bold"><RefreshCw size={16}/>تازه‌سازی</button></div>
 {error&&<div role="alert" className="mb-4 flex gap-2 rounded-xl bg-[#FFF1F1] p-4 text-sm text-[#A62B2B]"><AlertCircle size={18}/>{error}</div>}
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card=>{const Icon=card.icon;return <article key={card.label} className="rounded-2xl border border-[#E4EBE8] bg-white p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#E8F4F0] text-[#10706B]"><Icon size={19}/></span><p className="mt-4 text-xs text-[#87938F]">{card.label}</p><b className="mt-1 block text-2xl">{loading?"—":fa(card.value)}</b></article>})}</section>
 <section className="mt-5 overflow-hidden rounded-2xl border border-[#E4EBE8] bg-white"><div className="flex flex-col justify-between gap-3 border-b p-5 sm:flex-row sm:items-center"><div><h2 className="font-extrabold">وضعیت موجودی محصولات</h2><p className="mt-1 text-xs text-[#87938F]">از {fa(products.length)} محصول بارگذاری‌شده در این صفحه</p></div><Link href="/product-catalog" className="inline-flex items-center gap-1 text-xs font-bold text-[#10706B]">مدیریت کاتالوگ <ArrowLeft size={14}/></Link></div>
 {loading?<div className="p-10 text-center text-sm text-[#87938F]">در حال دریافت محصولات...</div>:products.length===0?<div className="p-10 text-center"><Database size={26} className="mx-auto text-[#87938F]"/><p className="mt-3 text-sm text-[#87938F]">محصولی در کاتالوگ دریافت نشد.</p></div>:<div className="divide-y divide-[#EDF1EF]">{products.slice(0,30).map(p=><div key={p.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#F2F7F5] text-[#10706B]"><Package size={18}/></span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{p.name}</b><small className="mt-1 block text-[10px] text-[#98A39F]" dir="ltr">{p.sku||p.id}</small></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${p.stockStatus==="OUT_OF_STOCK"||p.stock===0?"bg-[#FFF0F0] text-[#B42318]":p.stockStatus==="LOW_STOCK"?"bg-[#FFF2DF] text-[#9A650F]":"bg-[#E7F5EF] text-[#16835D]"}`}>{statusLabel(p)}</span><span className="min-w-14 text-left text-sm font-bold">{p.stock==null?"—":fa(p.stock)}</span></div></div>)}</div>}
 <div className="flex items-start gap-3 border-t bg-[#FAFCFB] p-4 text-xs leading-6 text-[#7D8D89]"><Sparkles size={16} className="mt-1 shrink-0 text-[#10706B]"/>اطلاعات موجودی باید از آخرین داده معتبر منبع محصول خوانده شود؛ این صفحه موجودی را حدس نمی‌زند و ادعای اجرای تحلیل AI ندارد.</div></section>
 </CustomerShell>;
}
