"use client";

import Link from "next/link";
import CustomerShell from "@/components/CustomerShell";
import { AlertCircle, ArrowLeft, CheckCircle2, CircleDashed, Clock3, Database, FileSearch, RefreshCw, Sparkles, WandSparkles, XCircle } from "lucide-react";

const stages=[{title:"دریافت اطلاعات",desc:"محصولات از منبع خوانده می‌شوند",icon:Database,state:"done"},{title:"پاک‌سازی و یکسان‌سازی",desc:"فیلدها و داده‌های تکراری بررسی می‌شوند",icon:FileSearch,state:"done"},{title:"تحلیل هوش مصنوعی",desc:"ویژگی‌ها و خلاصه محصول استخراج می‌شود",icon:WandSparkles,state:"active"},{title:"آماده‌سازی برای ایجنت",desc:"اطلاعات برای بازیابی در مکالمه آماده می‌شود",icon:Sparkles,state:"waiting"}];
const queue=[{name:"کفش روزمره مدل Air",sku:"SH-1042",status:"آماده استفاده",progress:100,tone:"done"},{name:"هدفون بی‌سیم Pro",sku:"EL-2081",status:"در حال تحلیل",progress:64,tone:"active"},{name:"کوله‌پشتی شهری",sku:"BG-1105",status:"نیازمند بررسی",progress:35,tone:"warning"},{name:"اسپیکر قابل حمل",sku:"EL-4301",status:"در صف پردازش",progress:0,tone:"waiting"}];
export default function ProductAnalysisPage(){return <CustomerShell><div className="mb-7"><p className="mb-2 text-xs font-bold text-[#10706B]">هوش محصول / تحلیل</p><h1 className="text-2xl font-black">تحلیل هوشمند محصولات</h1><p className="mt-2 text-sm text-[#7D8D89]">ببین اطلاعات محصولات در چه مرحله‌ای است و کدام مورد به بررسی نیاز دارد.</p></div>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{label:"محصولات تحلیل‌شده",value:"۱٬۱۹۷",sub:"آماده استفاده",icon:CheckCircle2,color:"text-[#16835D]",bg:"bg-[#E7F5EF]"},{label:"در صف پردازش",value:"۴۵",sub:"به‌زودی شروع می‌شود",icon:Clock3,color:"text-[#526AD4]",bg:"bg-[#EAF0FF]"},{label:"در حال تحلیل",value:"۲۱",sub:"در حال حاضر",icon:RefreshCw,color:"text-[#10706B]",bg:"bg-[#E8F4F0]"},{label:"نیازمند بررسی",value:"۲۱",sub:"اطلاعات ناقص یا مبهم",icon:AlertCircle,color:"text-[#B7791F]",bg:"bg-[#FFF2DF]"}].map(x=>{const Icon=x.icon;return <article key={x.label} className="rounded-2xl border border-[#E4EBE8] bg-white p-5"><span className={`grid h-10 w-10 place-items-center rounded-xl ${x.bg} ${x.color}`}><Icon size={19}/></span><p className="mt-4 text-xs text-[#87938F]">{x.label}</p><b className="mt-1 block text-2xl">{x.value}</b><p className="mt-1 text-[10px] text-[#87938F]">{x.sub}</p></article>})}</section>
 <section className="mt-5 rounded-2xl border border-[#E4EBE8] bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-extrabold">مراحل پردازش محصول</h2><p className="mt-1 text-xs text-[#87938F]">از دریافت اطلاعات تا آماده‌شدن برای پاسخ‌گویی ایجنت</p></div><span className="inline-flex items-center gap-2 rounded-full bg-[#E8F4F0] px-3 py-2 text-xs font-bold text-[#10706B]"><Sparkles size={14}/> گردش کار هوشمند</span></div><div className="mt-7 grid gap-4 md:grid-cols-4">{stages.map((s,i)=>{const Icon=s.icon;return <div key={s.title} className="relative rounded-2xl border border-[#E7ECEA] p-4">{i<stages.length-1&&<span className="absolute -left-3 top-8 hidden h-px w-3 bg-[#DCE7E3] md:block"/>}<span className={`grid h-10 w-10 place-items-center rounded-xl ${s.state==="done"?"bg-[#E7F5EF] text-[#16835D]":s.state==="active"?"bg-[#10706B] text-white":"bg-[#F0F3F2] text-[#96A19E]"}`}>{s.state==="done"?<CheckCircle2 size={19}/>:<Icon size={19}/>}</span><h3 className="mt-4 text-sm font-extrabold">{s.title}</h3><p className="mt-2 text-xs leading-6 text-[#87938F]">{s.desc}</p><span className={`mt-4 inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold ${s.state==="done"?"bg-[#E7F5EF] text-[#16835D]":s.state==="active"?"bg-[#E8F4F0] text-[#10706B]":"bg-[#F1F3F2] text-[#84918D]"}`}>{s.state==="done"?"تکمیل‌شده":s.state==="active"?"در حال اجرا":"در انتظار"}</span></div>})}</div></section>
 <section className="mt-5 overflow-hidden rounded-2xl border border-[#E4EBE8] bg-white"><div className="flex items-center justify-between border-b border-[#EDF1EF] px-5 py-4"><div><h2 className="font-extrabold">صف تحلیل محصولات</h2><p className="mt-1 text-xs text-[#87938F]">آخرین وضعیت پردازش کاتالوگ</p></div><Link href="/product-catalog" className="flex items-center gap-1 text-xs font-bold text-[#10706B]">مشاهده کاتالوگ <ArrowLeft size={14}/></Link></div><div className="divide-y divide-[#EDF1EF]">{queue.map(p=><div key={p.sku} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${p.tone==="done"?"bg-[#E7F5EF] text-[#16835D]":p.tone==="active"?"bg-[#E8F4F0] text-[#10706B]":p.tone==="warning"?"bg-[#FFF2DF] text-[#B7791F]":"bg-[#F1F3F2] text-[#84918D]"}`}>{p.tone==="done"?<CheckCircle2 size={18}/>:p.tone==="warning"?<AlertCircle size={18}/>:p.tone==="active"?<RefreshCw size={18}/>:<CircleDashed size={18}/>}</span><div className="min-w-0 flex-1"><b className="block text-sm">{p.name}</b><small className="mt-1 block text-[10px] text-[#98A39F]" dir="ltr">{p.sku}</small><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#EDF2F0]"><div className={`h-full rounded-full ${p.tone==="warning"?"bg-[#D7A04B]":"bg-[#10706B]"}`} style={{width:`${p.progress}%`}}/></div></div><div className="flex items-center justify-between gap-3 sm:w-40 sm:flex-col sm:items-end"><span className={`text-xs font-bold ${p.tone==="done"?"text-[#16835D]":p.tone==="warning"?"text-[#B7791F]":"text-[#74847F]"}`}>{p.status}</span><span className="text-[10px] text-[#98A39F]">{p.progress.toLocaleString("fa-IR")}٪</span></div></div>)}</div><div className="flex items-start gap-3 border-t border-[#EDF1EF] bg-[#FAFCFB] p-4 text-xs leading-6 text-[#7D8D89]"><AlertCircle size={16} className="mt-1 shrink-0 text-[#10706B]"/> تحلیل AI نباید قیمت یا موجودی را حدس بزند؛ این اطلاعات باید از آخرین داده معتبر منبع محصول دریافت شوند.</div></section>
 </CustomerShell>}
