"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import CustomerShell from "@/components/CustomerShell";
import { ArrowDownUp, ArrowLeft, Boxes, ChevronDown, CircleCheck, Download, Filter, Grid2X2, List, Package, Plus, Search, SlidersHorizontal, Sparkles } from "lucide-react";

const items=[
 {id:"SH-1042",name:"کفش روزمره مدل Air",category:"پوشاک",price:2490000,stock:42,source:"فروشگاه اینترنتی",state:"آماده",emoji:"👟",bg:"bg-[#E9F1EE]"},
 {id:"EL-2081",name:"هدفون بی‌سیم Pro",category:"الکترونیک",price:3850000,stock:18,source:"فروشگاه اینترنتی",state:"آماده",emoji:"🎧",bg:"bg-[#EDF0FA]"},
 {id:"BG-1105",name:"کوله‌پشتی شهری",category:"اکسسوری",price:1790000,stock:0,source:"فایل کاتالوگ",state:"نیازمند بررسی",emoji:"🎒",bg:"bg-[#F7EEE4]"},
 {id:"HM-3302",name:"چراغ رومیزی مینیمال",category:"خانه",price:1290000,stock:27,source:"فروشگاه اینترنتی",state:"آماده",emoji:"💡",bg:"bg-[#F6F1E2]"},
 {id:"EL-4301",name:"اسپیکر قابل حمل",category:"الکترونیک",price:2190000,stock:9,source:"فروشگاه اینترنتی",state:"در حال تحلیل",emoji:"🔊",bg:"bg-[#E8EFF4]"},
 {id:"AC-2910",name:"ساعت کلاسیک",category:"اکسسوری",price:4690000,stock:11,source:"فایل کاتالوگ",state:"آماده",emoji:"⌚",bg:"bg-[#F0EAF7]"},
];
const fmt=(n:number)=>new Intl.NumberFormat("fa-IR").format(n)+" تومان";
export default function ProductCatalogPage(){
 const [query,setQuery]=useState("");const [category,setCategory]=useState("همه دسته‌ها");const [state,setState]=useState("همه وضعیت‌ها");const [view,setView]=useState<"table"|"grid">("table");
 const filtered=useMemo(()=>items.filter(p=>(p.name+" "+p.id).toLowerCase().includes(query.toLowerCase())&&(category==="همه دسته‌ها"||p.category===category)&&(state==="همه وضعیت‌ها"||p.state===state)),[query,category,state]);
 const badge=(s:string)=>s==="آماده"?"bg-[#E7F5EF] text-[#16835D]":s==="در حال تحلیل"?"bg-[#EAF0FF] text-[#526AD4]":"bg-[#FFF2DF] text-[#A66B14]";
 return <CustomerShell><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold text-[#10706B]">هوش محصول / کاتالوگ</p><h1 className="text-2xl font-black">کاتالوگ محصولات</h1><p className="mt-2 text-sm text-[#7D8D89]">محصولات منابع متصل را مدیریت و وضعیت آمادگی آن‌ها برای ایجنت را بررسی کن.</p></div><Link href="/product-sources" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#10706B] px-4 py-3 text-sm font-bold text-white"><Plus size={16}/> افزودن منبع</Link></div>
 <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[#E4EBE8] bg-white p-4"><p className="text-xs text-[#87938F]">کل محصولات</p><b className="mt-2 block text-2xl">۱٬۲۸۴</b><span className="mt-1 block text-[11px] text-[#87938F]">از ۳ منبع</span></div><div className="rounded-2xl border border-[#E4EBE8] bg-white p-4"><p className="text-xs text-[#87938F]">آماده استفاده در AI</p><b className="mt-2 block text-2xl text-[#10706B]">۱٬۱۹۷</b><span className="mt-1 block text-[11px] text-[#87938F]">۹۳٪ کاتالوگ</span></div><div className="rounded-2xl border border-[#E4EBE8] bg-white p-4"><p className="text-xs text-[#87938F]">نیازمند بررسی</p><b className="mt-2 block text-2xl text-[#B7791F]">۲۱</b><span className="mt-1 block text-[11px] text-[#87938F]">خطا یا اطلاعات ناقص</span></div></div>
 <section className="mt-5 overflow-hidden rounded-2xl border border-[#E4EBE8] bg-white"><div className="flex flex-col gap-3 border-b border-[#EDF1EF] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative flex-1 sm:max-w-sm"><Search size={16} className="absolute right-3 top-3 text-[#87938F]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجوی نام یا SKU..." className="w-full rounded-xl border border-[#E1E9E5] py-2.5 pr-9 pl-3 text-xs outline-none focus:border-[#10706B]"/></div><div className="flex flex-wrap items-center gap-2"><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-[#E1E9E5] bg-white px-3 py-2.5 text-xs"><option>همه دسته‌ها</option>{["پوشاک","الکترونیک","اکسسوری","خانه"].map(x=><option key={x}>{x}</option>)}</select><select value={state} onChange={e=>setState(e.target.value)} className="rounded-xl border border-[#E1E9E5] bg-white px-3 py-2.5 text-xs"><option>همه وضعیت‌ها</option>{["آماده","نیازمند بررسی","در حال تحلیل"].map(x=><option key={x}>{x}</option>)}</select><div className="flex rounded-xl border border-[#E1E9E5] p-1"><button onClick={()=>setView("table")} className={`rounded-lg p-1.5 ${view==="table"?"bg-[#E8F4F0] text-[#10706B]":"text-[#87938F]"}`} aria-label="نمای جدولی"><List size={16}/></button><button onClick={()=>setView("grid")} className={`rounded-lg p-1.5 ${view==="grid"?"bg-[#E8F4F0] text-[#10706B]":"text-[#87938F]"}`} aria-label="نمای شبکه‌ای"><Grid2X2 size={16}/></button></div></div></div>
 {view==="table"?<div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right text-xs"><thead className="bg-[#F8FAF9] text-[#84918D]"><tr>{["محصول","دسته‌بندی","قیمت","موجودی","منبع","وضعیت تحلیل",""].map(x=><th key={x} className="px-5 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="border-t border-[#EDF1EF] hover:bg-[#FBFDFC]"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className={`grid h-10 w-10 place-items-center rounded-xl text-xl ${p.bg}`}>{p.emoji}</span><span><b className="block text-[13px]">{p.name}</b><small className="mt-1 block text-[#98A39F]" dir="ltr">{p.id}</small></span></div></td><td className="px-5 py-4">{p.category}</td><td className="px-5 py-4 whitespace-nowrap font-bold">{fmt(p.price)}</td><td className="px-5 py-4">{p.stock===0?<span className="text-[#C05656]">ناموجود</span>:new Intl.NumberFormat("fa-IR").format(p.stock)}</td><td className="px-5 py-4">{p.source}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${badge(p.state)}`}>{p.state}</span></td><td className="px-5 py-4"><button className="font-bold text-[#10706B]">جزئیات</button></td></tr>)}</tbody></table></div>:<div className="grid gap-4 p-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(p=><article key={p.id} className="rounded-2xl border border-[#E5ECE9] p-4"><div className={`grid h-28 place-items-center rounded-xl text-4xl ${p.bg}`}>{p.emoji}</div><div className="mt-4 flex items-start justify-between gap-2"><div><h3 className="text-sm font-extrabold">{p.name}</h3><p className="mt-1 text-[11px] text-[#87938F]">{p.category} · {p.id}</p></div><span className={`rounded-full px-2 py-1 text-[10px] ${badge(p.state)}`}>{p.state}</span></div><p className="mt-4 font-black">{fmt(p.price)}</p><p className="mt-2 text-xs text-[#87938F]">موجودی: {new Intl.NumberFormat("fa-IR").format(p.stock)}</p></article>)}</div>}
 <div className="flex items-center justify-between border-t border-[#EDF1EF] px-5 py-4 text-xs text-[#87938F]"><span>{new Intl.NumberFormat("fa-IR").format(filtered.length)} محصول نمایش داده می‌شود</span><Link href="/product-analysis" className="inline-flex items-center gap-1 font-bold text-[#10706B]">وضعیت تحلیل <ArrowLeft size={14}/></Link></div></section>
 </CustomerShell>
}
