"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import CustomerShell from "@/components/CustomerShell";
import { api } from "@/lib/api";
import { AlertCircle, Bot, LoaderCircle, RefreshCw, Save } from "lucide-react";

type Agent = { id: string; name: string; description?: string | null; systemPrompt: string; language: string; tone: string; isActive: boolean };
export default function CustomerAgentsPage(){
 const [agent,setAgent]=useState<Agent|null>(null);const [name,setName]=useState("");const [description,setDescription]=useState("");const [systemPrompt,setSystemPrompt]=useState("");const [language,setLanguage]=useState("fa");const [tone,setTone]=useState("friendly");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await api<{success:boolean;agent:Agent}>("/agent");setAgent(r.agent);setName(r.agent.name||"");setDescription(r.agent.description||"");setSystemPrompt(r.agent.systemPrompt||"");setLanguage(r.agent.language||"fa");setTone(r.agent.tone||"friendly");}catch(e){setAgent(null);setError(e instanceof Error?e.message:"دریافت ایجنت ناموفق بود.");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");setNotice("");try{const r=await api<{agent:Agent}>("/agent",{method:"PATCH",body:JSON.stringify({name,description,systemPrompt,language,tone})});setAgent(r.agent);setNotice("تنظیمات ایجنت ذخیره شد.");}catch(e){setError(e instanceof Error?e.message:"ذخیره تنظیمات ناموفق بود.");}finally{setBusy(false);}}
 async function toggle(){if(!agent)return;setBusy(true);setError("");try{const r=await api<{agent:Agent}>("/agent/toggle",{method:"PATCH",body:JSON.stringify({isActive:!agent.isActive})});setAgent(r.agent);setNotice(r.agent.isActive?"ایجنت فعال شد.":"ایجنت غیرفعال شد.");}catch(e){setError(e instanceof Error?e.message:"تغییر وضعیت ناموفق بود.");}finally{setBusy(false);}}
 return <CustomerShell><div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-2 text-xs font-bold text-[#10706B]">فضای کسب‌وکار</p><h1 className="text-2xl font-black">ایجنت‌های هوشمند</h1><p className="mt-2 text-sm text-[#7D8D89]">تنظیمات و وضعیت ایجنت از API حساب شما دریافت و ذخیره می‌شود.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-bold"><RefreshCw size={16}/>تازه‌سازی</button></div>
 {error&&<div role="alert" className="mb-4 flex gap-2 rounded-xl bg-[#FFF1F1] p-4 text-sm text-[#A62B2B]"><AlertCircle size={18}/>{error}</div>}{notice&&<p role="status" className="mb-4 rounded-xl bg-[#EFF9F4] p-3 text-sm text-[#176B4D]">{notice}</p>}
 {loading?<div className="flex justify-center gap-2 rounded-2xl border bg-white p-12 text-sm text-[#87938F]"><LoaderCircle size={18} className="animate-spin"/>در حال دریافت...</div>:agent?<form onSubmit={save} className="max-w-3xl rounded-2xl border border-[#E4EBE8] bg-white p-6"><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#E8F4F0] text-[#10706B]"><Bot size={22}/></span><div><h2 className="font-extrabold">{agent.name}</h2><p className="mt-1 text-xs text-[#87938F]">شناسه: {agent.id}</p></div></div><button type="button" onClick={()=>void toggle()} disabled={busy} className={`rounded-xl px-4 py-2 text-xs font-bold ${agent.isActive?"bg-[#E7F5EF] text-[#16835D]":"bg-[#FFF2DF] text-[#9A650F]"}`}>{agent.isActive?"فعال · توقف":"غیرفعال · فعال‌سازی"}</button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">نام ایجنت<input value={name} onChange={e=>setName(e.target.value)} required className="mt-2 w-full rounded-xl border px-3 py-3 text-sm font-normal"/></label><label className="text-xs font-bold">توضیحات<input value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm font-normal"/></label><label className="text-xs font-bold">زبان<select value={language} onChange={e=>setLanguage(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-3 py-3 text-sm font-normal"><option value="fa">فارسی</option><option value="en">English</option><option value="ar">العربية</option></select></label><label className="text-xs font-bold">لحن<select value={tone} onChange={e=>setTone(e.target.value)} className="mt-2 w-full rounded-xl border bg-white px-3 py-3 text-sm font-normal"><option value="friendly">دوستانه</option><option value="professional">حرفه‌ای</option><option value="formal">رسمی</option></select></label></div><label className="mt-4 block text-xs font-bold">دستورالعمل اصلی ایجنت<textarea value={systemPrompt} onChange={e=>setSystemPrompt(e.target.value)} rows={7} className="mt-2 w-full rounded-xl border px-3 py-3 text-sm font-normal leading-7"/></label><button disabled={busy} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#10706B] px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Save size={16}/>{busy?"در حال ذخیره...":"ذخیره تغییرات"}</button></form>:<div className="max-w-2xl rounded-2xl border bg-white p-8 text-center"><Bot size={28} className="mx-auto text-[#87938F]"/><h2 className="mt-3 font-extrabold">هنوز ایجنتی برای این حساب ساخته نشده</h2><p className="mt-2 text-sm text-[#87938F]">این API امکان دریافت و ویرایش ایجنت موجود را دارد؛ ساخت ایجنت از این صفحه هنوز فعال نشده است.</p></div>}</CustomerShell>;
}
